# -*- coding: utf-8 -*-
"""barplot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hK6rfcgZM8TCLkS0gW3X8auIZSnXnYdh
"""

import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

df = pd.read_csv("metrics1.csv")

# df.rename(columns={'smape': 'sMAPE', 'rrmse': 'RRMSE'}, inplace=True)

# metrics = list(df[['sMAPE','RRMSE']])

metrics = list(df[['MAPE']])

for metric in metrics:
    sns.set_style('whitegrid')
    g = sns.FacetGrid(df, col="dataset", aspect=0.8, height=4)
    g.map(sns.barplot, 'model', metric, 'forecasting_horizon', palette="Set1")
    g.add_legend(title='Forecasting Horizon')
    g.set_xlabels('Model')
    g.set_ylabels(metric)
    axes = g.axes.flatten()
    axes[0].set_title("Dataset 1")
    axes[1].set_title("Dataset 2")
    axes[2].set_title("Dataset 3")
    # g.savefig('boxplot_{}.png'.format(metric), dpi=300)
    # g.savefig('boxplot_{}.eps'.format(metric), dpi=300)
    # g.savefig('barplot_{}.pdf'.format(metric), dpi=300)
    plt.show()